sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
script:
   - npm run coveralls
notifications:
  irc: "irc.freenode.org#brass-monkey"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
